get:
  tags:
    - Cardano » Epochs
  summary: Latest epoch protocol parameters
  description: Return the protocol parameters for the latest epoch.
  responses:
    "200":
      description: Return the data about the epoch
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/epoch_param_content"
    "400":
      $ref: "#/components/responses/bad_request"
    "403":
      $ref: "#/components/responses/unauthorized_error"
    "404":
      $ref: "#/components/responses/not_found"
    "429":
      $ref: "#/components/responses/overusage_limit"
    "418":
      $ref: "#/components/responses/autobanned"
    "500":
      $ref: "#/components/responses/internal_server_error"
